### PR TITLE
feat(search): Integration of new search-panel

### PR DESCRIPTION
**Pull request by kilchenmann**
This PR needs the @knora/search module from branch [wip/search-simplify](https://github.com/dhlab-basel/Knora-ui/tree/wip/search-simplify)

### CODE REVIEW

**Comment by flavens** [comment]
@kilchenmann I will review this PR when the tests will pass if this is ok for you

**Comment by kilchenmann** [comment]
Yes of course... I fix the tests first

**Review by flavens — COMMENTED** [review]
A few things (do not know if this is what you wanted):
- when I switch to other search bars and go back to the first selected one, the search log/history does not appear anymore
- there is still some issues when reloading the content after a new search
- the icon when you combine advanced and expert searches is not obvious to me..

**Comment by kilchenmann** [comment]
> A few things (do not know if this is what you wanted):
> 
> * when I switch to other search bars and go back to the first selected one, the search log/history does not appear anymore

--> yes that's right. When I keep the search log for the different views I have some items twice, because I filtered by various projects first (ding in Anything, and ding in Incunabula etc.) and when I switch back to simple fulltext-search I have the same search query more than once in the list.

> * there is still some issues when reloading the content after a new search

I changed nothing in the search request or in the search results. This PR is just the optimization of search-panel

> * the icon when you combine advanced and expert searches is not obvious to me..

It's just a suggestion. I wanted to have something like "filter" icon which doesn't exist in the material icon.

**Review by flavens — APPROVED** [review]

**Pull request merged**
